# Site settings
title: Corentin Schreiber
email: cschreib@strw.leidenuniv.nl
description: > # this means to ignore newlines until "baseurl:"
  Personal website of Corentin Schreiber. Read about astrophysics and
  the evolution of galaxies, as well as more technical stuff about coding
  in C++.
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  cschreib

# Build settings
markdown: kramdown
